"""initial business schema

Revision ID: 599060c4e057
Revises: 
Create Date: 2026-08-22 01:31:08.817491+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '599060c4e057'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_state',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('members', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allocation_state'))
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('menus', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('notice', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('page_contents', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_table('edit_logs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), server_default='', nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('user_email', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edit_logs'))
    )
    op.create_index('ix_edit_logs_time_desc', 'edit_logs', [sa.literal_column('time DESC')], unique=False)
    op.create_table('group_review_projects',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('members', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_email', sa.Text(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_by_email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_by_email', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_review_projects'))
    )
    op.create_table('schedules',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('memo', sa.Text(), server_default='', nullable=False),
    sa.Column('color', sa.Text(), server_default='#3b82f6', nullable=False),
    sa.Column('writer_email', sa.Text(), server_default='anonymous', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('start_time IS NULL OR end_time IS NULL OR start_time <= end_time', name=op.f('ck_schedules_start_time_before_end_time')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_index('ix_schedules_date', 'schedules', ['date'], unique=False)
    op.create_table('allocation_projects',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('state_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('memo', sa.Text(), server_default='', nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('rows', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['allocation_state.id'], name=op.f('fk_allocation_projects_state_id_allocation_state'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allocation_projects'))
    )
    op.create_table('group_review_sheets',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('member_name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), server_default='member', nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('review_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('review_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_completed_by_email', sa.Text(), nullable=True),
    sa.Column('reuse_requested', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reuse_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reuse_requested_by', sa.Text(), nullable=True),
    sa.Column('reuse_requested_by_email', sa.Text(), nullable=True),
    sa.Column('reuse_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reuse_approved_by_email', sa.Text(), nullable=True),
    sa.Column('reuse_request_rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reuse_request_rejected_by_email', sa.Text(), nullable=True),
    sa.Column('lock_session_id', sa.Text(), nullable=True),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('updated_by_email', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['group_review_projects.id'], name=op.f('fk_group_review_sheets_project_id_group_review_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_review_sheets')),
    sa.UniqueConstraint('project_id', 'member_name', name=op.f('uq_group_review_sheets_project_id_member_name'))
    )
    op.create_table('group_review_rows',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('sheet_id', sa.BigInteger(), nullable=False),
    sa.Column('firestore_row_id', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('parent_revision_row_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_revision_firestore_row_id', sa.Text(), nullable=True),
    sa.Column('collateral_no', sa.Text(), server_default='', nullable=False),
    sa.Column('sheet_label', sa.Text(), server_default='', nullable=False),
    sa.Column('field_no', sa.Text(), server_default='', nullable=False),
    sa.Column('checked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('change_before_text', sa.Text(), server_default='', nullable=False),
    sa.Column('change_before_html', sa.Text(), server_default='', nullable=False),
    sa.Column('change_after_text', sa.Text(), server_default='', nullable=False),
    sa.Column('change_after_html', sa.Text(), server_default='', nullable=False),
    sa.Column('review_status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('revision_no', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_email', sa.Text(), nullable=True),
    sa.Column('revision_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision_requested_by_email', sa.Text(), nullable=True),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("review_status IN ('draft', 'submitted', 'approved', 'revision_requested')", name=op.f('ck_group_review_rows_review_status_allowed')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_group_review_rows_position_nonnegative')),
    sa.CheckConstraint('revision_no >= 1', name=op.f('ck_group_review_rows_revision_no_positive')),
    sa.ForeignKeyConstraint(['parent_revision_row_id'], ['group_review_rows.id'], name=op.f('fk_group_review_rows_parent_revision_row_id_group_review_rows'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sheet_id'], ['group_review_sheets.id'], name=op.f('fk_group_review_rows_sheet_id_group_review_sheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_review_rows')),
    sa.UniqueConstraint('sheet_id', 'firestore_row_id', name=op.f('uq_group_review_rows_sheet_id_firestore_row_id')),
    sa.UniqueConstraint('sheet_id', 'position', name=op.f('uq_group_review_rows_sheet_id_position'))
    )
    op.create_index('ix_group_review_rows_parent_revision_firestore_row_id', 'group_review_rows', ['parent_revision_firestore_row_id'], unique=False)
    op.create_index('ix_group_review_rows_sheet_id_review_status', 'group_review_rows', ['sheet_id', 'review_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_group_review_rows_sheet_id_review_status', table_name='group_review_rows')
    op.drop_index('ix_group_review_rows_parent_revision_firestore_row_id', table_name='group_review_rows')
    op.drop_table('group_review_rows')
    op.drop_table('group_review_sheets')
    op.drop_table('allocation_projects')
    op.drop_index('ix_schedules_date', table_name='schedules')
    op.drop_table('schedules')
    op.drop_table('group_review_projects')
    op.drop_index('ix_edit_logs_time_desc', table_name='edit_logs')
    op.drop_table('edit_logs')
    op.drop_table('app_settings')
    op.drop_table('allocation_state')
    # ### end Alembic commands ###
